### ISSUE TITLE
Supports Windows XP

### ISSUE THREAD

**Issue by zeze-zeze** [trailofbits/uthenticode#101]
I use this project in Windows XP SP3 and it makes an exception and outputs the error message "bcrypt.dll not found". After some surveys, it turned out that XP doesn't have bcrypt.dll in the system by default. But even if I copy a bcrypt.dll to the same directory, it still has the error message "InitializeSRWLock not found in Kernel32.dll". It seems there are some dependencies in this project that XP doesn't have.

Is there any solution or workaround for XP to use this project?

**Comment by woodruffw** [comment]
> Is there any solution or workaround for XP to use this project?

None that I'm aware of; I've never tested this on any version of Windows below 10. I would be happy to consider a patch that supports XP, assuming it's not overly burdensome for versions of Windows (and other supported platforms) that are still supported by their companies/upstreams.

**Comment by zeze-zeze** [comment]
Looks like the dependency that makes an exception is OpenSSL. I used OpenSSL 3.0.2 in vcpkg to build uthenticode, but it uses some functions which don't work on XP.

According to ["bcrypt.dll was not found" after compiling for Windows XP.](https://github.com/openssl/openssl/issues/8635), we need to compile OpenSSL with an option `-D_WIN32_WINNT=0x0501`.

**Comment by zeze-zeze** [comment]
Finally, after some effort, I built OpenSSL by following [Building OpenSSL on Windows](https://docs.rocketsoftware.com/bundle/unidatasecurity_ag_831/page/lpe1705530869388.html), then imported libcrypto.lib and libssl.lib into the project and it worked on XP!

**Comment by zeze-zeze** [comment]
Not sure if this issue is still needed because it seems not to be an issue for uthenticode. Maybe add some tutorials about how to make it work on XP, or just close the issue.
