### ISSUE TITLE
Shouldn't this instance here be a std::make_unique?

### ISSUE THREAD

**Issue by hugmyndakassi** [trailofbits/uthenticode#105]
This instance in `WinCert::as_signed_data()`:

```
return std::unique_ptr<SignedData>(new SignedData(cert_buf_));
```

**Comment by woodruffw** [comment]
My understanding is that `std::unique_ptr`'s ctor and `std::make_unique` are semantically equivalent, so there's no harm in the current form. But using `make_unique` with argument forwarding is maybe a little more idiomatic? If that's the case, feel free to send a PR 🙂

**Comment by hugmyndakassi** [comment]
That's what I meant. And as far as I understand it there is one edge case where they behave differently, but that's mostly important when passing unique pointers into an argument list (not the case here).
